export const STATUS_COLORS = {
	online: '#2de0a5',
	busy: '#f5455c',
	away: '#ffd21f',
	offline: '#cbced1'
};

export const SWITCH_TRACK_COLOR = {
	false: '#f5455c',
	true: '#2de0a5'
};

const mentions = {
	unreadColor: '#6C727A',
	tunreadColor: '#2c7fbd',
	mentionMeColor: '#F5455C',
	mentionGroupColor: '#F38C39',
	mentionOtherColor: '#F3BE08'
};

export const themes = {
	light: {
		backgroundColor: '#ffffff',
		focusedBackground: '#dfdfdf',
		chatComponentBackground: '#f3f4f5',
		auxiliaryBackground: '#efeff4',
		bannerBackground: '#dfdfdf',
		titleText: '#2f343d',
		bodyText: '#2f343d',
		backdropColor: '#000000',
		dangerColor: '#f5455c',
		successColor: '#2de0a5',
		borderColor: '#e1e5e8',
		controlText: '#2f343d',
		auxiliaryText: '#2f343d',
		infoText: '#2f343d',
		tintColor: '#2c7fbd',
		tintActive: '#549df9',
		auxiliaryTintColor: '#6C727A',
		actionTintColor: '#2c7fbd',
		separatorColor: '#2c7fbd',
		navbarBackground: '#dfdfdf',
		headerBorder: '#9ca2a8',
		headerBackground: '#2c7fbd',
		headerSecondaryBackground: '#ffffff',
		headerTintColor: '#E6E6E7',
		headerTitleColor: '#efeff4',
		headerSecondaryText: '#E6E6E7',
		toastBackground: '#0C0D0F',
		videoBackground: '#1f2329',
		favoriteBackground: '#2c7fbd',
		hideBackground: '#54585e',
		messageboxBackground: '#ffffff',
		searchboxBackground: '#E6E6E7',
		buttonBackground: '#2c7fbd',
		buttonText: '#ffffff',
		passcodeBackground: '#EEEFF1',
		passcodeButtonActive: '#E4E7EA',
		passcodeLockIcon: '#6C727A',
		passcodePrimary: '#2F343D',
		passcodeSecondary: '#6C727A',
		passcodeDotEmpty: '#CBCED1',
		passcodeDotFull: '#6C727A',
		previewBackground: '#1F2329',
		previewTintColor: '#ffffff',
		...mentions
	},
	dark: {
		backgroundColor: '#030b1b',
		focusedBackground: '#0b182c',
		chatComponentBackground: '#192132',
		auxiliaryBackground: '#07101e',
		bannerBackground: '#0e1f38',
		titleText: '#f9f9f9',
		bodyText: '#e8ebed',
		backdropColor: '#000000',
		dangerColor: '#f5455c',
		successColor: '#2de0a5',
		borderColor: '#0f213d',
		controlText: '#dadde6',
		auxiliaryText: '#9297a2',
		infoText: '#6D6D72',
		tintColor: '#f9f9f9',
		tintActive: '#2c7fbd',
		auxiliaryTintColor: '#f9f9f9',
		actionTintColor: '#2c7fbd',
		separatorColor: '#2c7fbd',
		navbarBackground: '#2c7fbd',
		headerBorder: '#323232',
		headerBackground: '#2c7fbd',
		headerSecondaryBackground: '#2c7fbd',
		headerTintColor: '#f9f9f9',
		headerTitleColor: '#f9f9f9',
		headerSecondaryText: '#e8ebed',
		toastBackground: '#0C0D0F',
		videoBackground: '#1f2329',
		favoriteBackground: '#2c7fbd',
		hideBackground: '#54585e',
		messageboxBackground: '#2c7fbd',
		searchboxBackground: '#dfdfdf',
		buttonBackground: '#2c7fbd',
		buttonText: '#ffffff',
		passcodeBackground: '#030C1B',
		passcodeButtonActive: '#0B182C',
		passcodeLockIcon: '#6C727A',
		passcodePrimary: '#FFFFFF',
		passcodeSecondary: '#CBCED1',
		passcodeDotEmpty: '#CBCED1',
		passcodeDotFull: '#6C727A',
		previewBackground: '#030b1b',
		previewTintColor: '#ffffff',
		...mentions
	},
	black: {
		backgroundColor: '#000000',
		focusedBackground: '#0d0d0d',
		chatComponentBackground: '#16181a',
		auxiliaryBackground: '#080808',
		bannerBackground: '#1f2329',
		titleText: '#f9f9f9',
		bodyText: '#e8ebed',
		backdropColor: '#000000',
		dangerColor: '#f5455c',
		successColor: '#2de0a5',
		borderColor: '#1f2329',
		controlText: '#dadde6',
		auxiliaryText: '#b2b8c6',
		infoText: '#CBCED1',
		tintColor: '#2c7fbd',
		tintActive: '#2c7fbd',
		auxiliaryTintColor: '#f9f9f9',
		actionTintColor: '#2c7fbd',
		separatorColor: '#272728',
		navbarBackground: '#2c7fbd',
		headerBorder: '#323232',
		headerBackground: '#2c7fbd',
		headerSecondaryBackground: '#2c7fbd',
		headerTintColor: '#e6e6e6',
		headerTitleColor: '#e6e6e6',
		headerSecondaryText: '#e8ebed',
		toastBackground: '#0C0D0F',
		videoBackground: '#1f2329',
		favoriteBackground: '#2c7fbd',
		hideBackground: '#54585e',
		messageboxBackground: '#0d0d0d',
		searchboxBackground: '#dfdfdf',
		buttonBackground: '#2c7fbd',
		buttonText: '#ffffff',
		passcodeBackground: '#000000',
		passcodeButtonActive: '#0E0D0D',
		passcodeLockIcon: '#6C727A',
		passcodePrimary: '#FFFFFF',
		passcodeSecondary: '#CBCED1',
		passcodeDotEmpty: '#CBCED1',
		passcodeDotFull: '#6C727A',
		previewBackground: '#000000',
		previewTintColor: '#ffffff',
		...mentions
	}
};
